### ISSUE TITLE
GENERAL CHECKLIST!!!

### ISSUE THREAD

**Issue by Amawers** [SIPIAR-CAPSTONE/admin#20]
- [ ] remove bug report (ADMIN, AND BYSTANDER)
- [ ] dapat naay responder name, of response time (column) kada incident record sa incident history table and incident info page (ADMIN)
- [ ] walaon ang id sa mga table. change it to something useful (who, where, etc.) like bystander name, Responder name. (ADMIN)
